### ISSUE TITLE
Issues syntax requests

### ISSUE THREAD

**Issue by mattgraham** [tombell/hubot-github-issues#2]
Dreaming through what issues should look like these first thoughts come to mind. 

- [ ] Issues List
![screenshot 2014-08-30 17 37 23](https://cloud.githubusercontent.com/assets/51578/4100298/f08c1d08-308d-11e4-8227-e73f816020d1.png)

- [ ] Issue List with Scope
![screenshot 2014-08-30 17 43 44](https://cloud.githubusercontent.com/assets/51578/4100314/bb06257e-308e-11e4-9fa6-1f08f2455695.png)

- [ ] Search
![screenshot 2014-08-30 17 38 28](https://cloud.githubusercontent.com/assets/51578/4100299/fd2d9384-308d-11e4-8b6f-5a0fd631c52b.png)

- [ ] Create
![screenshot 2014-08-30 17 46 50](https://cloud.githubusercontent.com/assets/51578/4100318/2817b150-308f-11e4-9d4c-99d3a68d9fb8.png)

- [ ] Oldest 10 / Newest / Recently Updated etc. (this can use the Sort by filters via GitHub)
![screenshot 2014-08-30 17 51 54](https://cloud.githubusercontent.com/assets/51578/4100327/eb95d8a0-308f-11e4-88bb-1262b5b899c0.png)

**Comment by n0mer** [comment]
:+1: for issues list
