### ISSUE TITLE
Identification does not work

### ISSUE THREAD

**Issue by omnidan** [tombell/hubot-github-issues#3]
I identified myself with the web service and now `who am I` seems to work fine:

    omnidan: You are known as omnidan on GitHub

However, `issues comment` does not work:

    omnidan: Sorry, you haven't told me your GitHub username.

**Comment by tombell** [comment]
It's been over a year since I made this project, and it was never really "released", so I can't really debug what's going wrong.

**Comment by omnidan** [comment]
@tombell Aw, that sucks. I'll try to look into it myself then when I get around it :grin: Thanks anyways!
